language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

env:
  matrix:
   - DB=MYSQL CORE_RELEASE=3.0
   - DB=MYSQL CORE_RELEASE=3.1
   - DB=MYSQL CORE_RELEASE=3.2

matrix:
  allow_failures:
    - php: 7.0
  include:
    - php: 5.3
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=master
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=master      
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=master

before_script:
  - phpenv rehash
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit silverstripe-spamprotection-honeypot/tests --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
